# lec 81

## Numpy part-3

In [1]:
import numpy as np
# Numpy-Array Manipulation

In [2]:
arr=np.random.randint(1,11,(4,4))

In [3]:
arr

array([[ 1,  1, 10,  6],
       [ 4, 10,  8,  9],
       [ 3,  6,  5,  3],
       [ 1,  3,  4,  1]])

In [4]:
arr.reshape(8,2)

array([[ 1,  1],
       [10,  6],
       [ 4, 10],
       [ 8,  9],
       [ 3,  6],
       [ 5,  3],
       [ 1,  3],
       [ 4,  1]])

In [6]:
arr.T  # transpose of a matrix

array([[ 1,  4,  3,  1],
       [ 1, 10,  6,  3],
       [10,  8,  5,  4],
       [ 6,  9,  3,  1]])

In [8]:
arr.flatten() # converting the matrix into single dimension matrix

array([ 1,  1, 10,  6,  4, 10,  8,  9,  3,  6,  5,  3,  1,  3,  4,  1])

In [9]:
arr

array([[ 1,  1, 10,  6],
       [ 4, 10,  8,  9],
       [ 3,  6,  5,  3],
       [ 1,  3,  4,  1]])

In [10]:
np.expand_dims(arr,axis=1) # increases the dimension by 1 

array([[[ 1,  1, 10,  6]],

       [[ 4, 10,  8,  9]],

       [[ 3,  6,  5,  3]],

       [[ 1,  3,  4,  1]]])

In [11]:
np.expand_dims(arr,axis=0)

array([[[ 1,  1, 10,  6],
        [ 4, 10,  8,  9],
        [ 3,  6,  5,  3],
        [ 1,  3,  4,  1]]])

In [12]:
data=np.array([[1],[2],[3]])

In [13]:
np.squeeze(data)

array([1, 2, 3])

In [14]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [15]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [17]:
np.roll(data,2) # it means two places will be exchanged .. simply rolling .moving to the next place in clockwise direction

array([[2],
       [3],
       [1]])

In [19]:
np.diag(np.array([1,2,3,4])) # representing into the diagonal matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Binary operations

In [21]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,5,(3,4))

In [22]:
arr1

array([[9, 4, 1, 2],
       [6, 4, 7, 7],
       [3, 9, 2, 2]])

In [23]:
arr2

array([[2, 3, 3, 1],
       [2, 4, 4, 1],
       [2, 1, 1, 3]])

In [24]:
arr1+arr2 # index wise addition

array([[11,  7,  4,  3],
       [ 8,  8, 11,  8],
       [ 5, 10,  3,  5]])

In [25]:
arr1*arr2 # index wise multiplication

array([[18, 12,  3,  2],
       [12, 16, 28,  7],
       [ 6,  9,  2,  6]])

In [27]:
arr1/arr2 # index wise division

array([[4.5       , 1.33333333, 0.33333333, 2.        ],
       [3.        , 1.        , 1.75      , 7.        ],
       [1.5       , 9.        , 2.        , 0.66666667]])

In [29]:
arr1@arr2 # matrix multiplication is not possible here.

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [30]:
arr1-arr2

array([[ 7,  1, -2,  1],
       [ 4,  0,  3,  6],
       [ 1,  8,  1, -1]])

In [31]:
arr1**arr2

array([[  81,   64,    1,    2],
       [  36,  256, 2401,    7],
       [   9,    9,    2,    8]], dtype=int32)

In [32]:
~arr1

array([[-10,  -5,  -2,  -3],
       [ -7,  -5,  -8,  -8],
       [ -4, -10,  -3,  -3]], dtype=int32)

In [33]:
arr1>arr2

array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False]])

# string functions

In [34]:
arr=np.array(['indra',"raghu"],dtype='<U5')

In [35]:
arr

array(['indra', 'raghu'], dtype='<U5')

In [37]:
np.char.upper(arr) # converting into the upper case

array(['INDRA', 'RAGHU'], dtype='<U5')

In [38]:
np.char.title(arr)

array(['Indra', 'Raghu'], dtype='<U5')

In [39]:
np.char.capitalize(arr)

array(['Indra', 'Raghu'], dtype='<U5')

# Mathematical functions

In [41]:
arr1

array([[9, 4, 1, 2],
       [6, 4, 7, 7],
       [3, 9, 2, 2]])

In [43]:
np.sin(arr1)

array([[ 0.41211849, -0.7568025 ,  0.84147098,  0.90929743],
       [-0.2794155 , -0.7568025 ,  0.6569866 ,  0.6569866 ],
       [ 0.14112001,  0.41211849,  0.90929743,  0.90929743]])

In [44]:
np.tan(arr1)

array([[-0.45231566,  1.15782128,  1.55740772, -2.18503986],
       [-0.29100619,  1.15782128,  0.87144798,  0.87144798],
       [-0.14254654, -0.45231566, -2.18503986, -2.18503986]])

In [45]:
np.log(arr1)

array([[2.19722458, 1.38629436, 0.        , 0.69314718],
       [1.79175947, 1.38629436, 1.94591015, 1.94591015],
       [1.09861229, 2.19722458, 0.69314718, 0.69314718]])

In [46]:
np.exp(arr1)

array([[8.10308393e+03, 5.45981500e+01, 2.71828183e+00, 7.38905610e+00],
       [4.03428793e+02, 5.45981500e+01, 1.09663316e+03, 1.09663316e+03],
       [2.00855369e+01, 8.10308393e+03, 7.38905610e+00, 7.38905610e+00]])

In [47]:
np.cos(arr1)

array([[-0.91113026, -0.65364362,  0.54030231, -0.41614684],
       [ 0.96017029, -0.65364362,  0.75390225,  0.75390225],
       [-0.9899925 , -0.91113026, -0.41614684, -0.41614684]])

In [48]:
np.power(arr1,2)

array([[81, 16,  1,  4],
       [36, 16, 49, 49],
       [ 9, 81,  4,  4]], dtype=int32)

In [49]:
np.mean(arr1)

4.666666666666667

In [50]:
np.median(arr1)

4.0

In [51]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [52]:
np.std(arr1)

2.718251071716682

In [53]:
np.var(arr1)

7.388888888888889

In [54]:
np.min(arr1)

1

In [55]:
np.max(arr1)

9

# Aritmetic operations

In [57]:
arr1

array([[9, 4, 1, 2],
       [6, 4, 7, 7],
       [3, 9, 2, 2]])

In [58]:
arr1+5

array([[14,  9,  6,  7],
       [11,  9, 12, 12],
       [ 8, 14,  7,  7]])

In [59]:
arr1-arr2

array([[ 7,  1, -2,  1],
       [ 4,  0,  3,  6],
       [ 1,  8,  1, -1]])

In [60]:
np.subtract(arr1,arr2)

array([[ 7,  1, -2,  1],
       [ 4,  0,  3,  6],
       [ 1,  8,  1, -1]])

In [61]:
np.multiply(arr1,arr2)

array([[18, 12,  3,  2],
       [12, 16, 28,  7],
       [ 6,  9,  2,  6]])

In [62]:
np.mod(arr1,arr2) # mod means modulus operation here

array([[1, 1, 1, 0],
       [0, 0, 3, 0],
       [1, 0, 0, 2]], dtype=int32)

In [63]:
np.power(arr1,arr2)

array([[  81,   64,    1,    2],
       [  36,  256, 2401,    7],
       [   9,    9,    2,    8]], dtype=int32)

In [64]:
np.sqrt(arr1)

array([[3.        , 2.        , 1.        , 1.41421356],
       [2.44948974, 2.        , 2.64575131, 2.64575131],
       [1.73205081, 3.        , 1.41421356, 1.41421356]])

In [65]:
np.mean(arr1)

4.666666666666667

# lec 82
## Numpy part 4

In [66]:
# sort ,search and counting functions

In [71]:
a=np.array([2,3,4,5,6,7,12,43,32,11,78,10])

In [72]:
a

array([ 2,  3,  4,  5,  6,  7, 12, 43, 32, 11, 78, 10])

In [73]:
np.sort(a) # ascending order

array([ 2,  3,  4,  5,  6,  7, 10, 11, 12, 32, 43, 78])

In [77]:
np.searchsorted(a,8) # find indices where elements should be inserted to manintain order.

6

In [79]:
np.searchsorted(a,123)

12

In [81]:
np.searchsorted(a,40)

12

In [82]:
np.searchsorted(a,1) # at 0 th position we can insert this and preserved the order

0

In [83]:
a1=np.array([1,2,3,4,0,0,7,6,5,4,3,7,8,9,2,4,0]) # array index starts from zero

In [86]:
np.count_nonzero(a1) # gives no of non zero elements present in the array

14

In [89]:
np.where(a1>7) # gives all the indices where the indices are greater than 7

(array([12, 13], dtype=int64),)

In [92]:
np.extract(a1>6,a1) # extracts all the data which are greater than the given element


array([7, 7, 8, 9])

In [93]:
a1

array([1, 2, 3, 4, 0, 0, 7, 6, 5, 4, 3, 7, 8, 9, 2, 4, 0])

In [94]:
# Byte Swapping

In [95]:
# for every data ,it will give the byte representation present in the memory.
a1.byteswap() # swaps the original data into the bytes present in the memory.

array([ 16777216,  33554432,  50331648,  67108864,         0,         0,
       117440512, 100663296,  83886080,  67108864,  50331648, 117440512,
       134217728, 150994944,  33554432,  67108864,         0])

In [96]:
a1.byteswap(True)


array([ 16777216,  33554432,  50331648,  67108864,         0,         0,
       117440512, 100663296,  83886080,  67108864,  50331648, 117440512,
       134217728, 150994944,  33554432,  67108864,         0])

In [97]:
a1

array([ 16777216,  33554432,  50331648,  67108864,         0,         0,
       117440512, 100663296,  83886080,  67108864,  50331648, 117440512,
       134217728, 150994944,  33554432,  67108864,         0])

In [98]:
a1

array([ 16777216,  33554432,  50331648,  67108864,         0,         0,
       117440512, 100663296,  83886080,  67108864,  50331648, 117440512,
       134217728, 150994944,  33554432,  67108864,         0])

In [99]:
a

array([ 2,  3,  4,  5,  6,  7, 12, 43, 32, 11, 78, 10])

# Copies and Views

In [103]:
a2=np.copy(a) # deep copy

In [102]:
a2

array([ 2,  3,  4,  5,  6,  7, 12, 43, 32, 11, 78, 10])

In [119]:
a21=a.view() # just like a shallow copy.. changing one variable elements changes another place elements also.

In [120]:
a21

array([109,   3,   4,   5,   6,   7,  12,  43,  32,  11,  78,  10])

In [121]:
a21[0]=109

In [122]:
a21

array([109,   3,   4,   5,   6,   7,  12,  43,  32,  11,  78,  10])

In [123]:
a

array([109,   3,   4,   5,   6,   7,  12,  43,  32,  11,  78,  10])

# Numpy-Matrix Libraray

In [125]:
import numpy.matlib as nm

In [126]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [127]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [128]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

# Linear Algebra

In [129]:
a

array([109,   3,   4,   5,   6,   7,  12,  43,  32,  11,  78,  10])

In [130]:
c1=np.random.randint([[2,3],[4,5]]) 

In [131]:
c1

array([[1, 2],
       [3, 0]])

In [134]:
c2=np.random.randint([[5,3],[4,3]])

In [135]:
c2

array([[2, 0],
       [2, 0]])

In [136]:
np.dot(1,c2) # dot product of two arrays

array([[2, 0],
       [2, 0]])

In [138]:
c1@c2

array([[6, 0],
       [6, 0]])