# lec 79
## Numpy Part 1

In [1]:
# Numpy means Numerical Python
# used to calculate/perform specific operations on the arrays or matrices

In [2]:
list1=[1,2,3,4,5,6]

In [3]:
# we have to import numpy module for using the Numpy related functions


In [4]:
import numpy as np

In [7]:
arr1=np.array(list1) # converting the list to array

In [8]:
arr1

array([1, 2, 3, 4, 5, 6])

In [90]:
print(arr1) # in arrays commas should not present .

[200   2   3   4   5   6]


In [9]:
# we can convert in one more way as shown below

In [11]:
list2=([1,2,3],[4,5,6])

In [12]:
arr2=np.asarray(list2)

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.ndim

2

In [15]:
arr1.ndim

1

In [16]:
type(arr1)

numpy.ndarray

In [17]:
type(arr2)

numpy.ndarray

In [18]:
# let us see the matrices here
mat1=np.matrix(list1)

In [20]:
mat1 # Matrices are always having 2 dim where as arrays will have single dimension also.

matrix([[1, 2, 3, 4, 5, 6]])

In [26]:
# asanyarray function will converts anything into array if it not available in the form  of array
# matrix is subclass of array inside the numpy. so no changes will be done.
np.asanyarray(list1) # converts the list to array

array([1, 2, 3, 4, 5, 6])

In [27]:
# 
np.asanyarray(mat1) # since matrix is subclass of an array ,so there is no changes made here

matrix([[1, 2, 3, 4, 5, 6]])

In [28]:
arr1

array([1, 2, 3, 4, 5, 6])

In [31]:
a=arr1 # both are having the same data

In [32]:
a

array([1, 2, 3, 4, 5, 6])

In [33]:
# here above we performed the shallow copy operation which means any change in one variable will results same changes in another variable also

In [34]:
arr1[0]=200

In [36]:
a # see the same change occured here also

array([200,   2,   3,   4,   5,   6])

In [37]:
# deep copy --> creates a separate memory and copies it 
b=np.copy(arr2)

In [38]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b[0][1]=150

In [40]:
b

array([[  1, 150,   3],
       [  4,   5,   6]])

In [42]:
arr2 # no changes will occur since it will create the new copy and not used as reference

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# it takes the function as argument here and generates the dataset.
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [47]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [50]:
np.fromfunction(lambda i,j:i-j,(3,3))

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [54]:
a=(i*i for i in  range(10)) # creates a generator object here.

In [55]:
list(a) # to convert the above iterator as output we used list here

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [56]:
# generate it using numpy

In [57]:
iterable=(i*i for i in  range(10))

In [58]:
np.fromiter(iterable,float) # fromiter will converts the above iterable to array form with the required format mentioned

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [60]:
np.fromstring('23 45 6 7',sep=" ") # most of the outcomes in the numpy are arrays only

array([23., 45.,  6.,  7.])

In [63]:
np.fromstring('23,45,67',sep=",") # wherever comma is present , it will separate them and put them into array

array([23., 45., 67.])

In [64]:
arr1

array([200,   2,   3,   4,   5,   6])

In [66]:
arr1.ndim

1

In [68]:
arr2.size # total no of elements in the array

6

In [69]:
arr1.shape # 6 rows are present

(6,)

In [71]:
arr2.shape # 2 rows and 3 columns are present

(2, 3)

In [73]:
arr1.dtype # gives the datatype

dtype('int32')

# lec 80
##  numpy part 2  

In [74]:
range(5)

range(0, 5)

In [79]:
a=list(range(5))
a

[0, 1, 2, 3, 4]

In [78]:
np.array(a)

array([0, 1, 2, 3, 4])

In [82]:
list(range(0.3,10.5)) # range function will takes only integers as input whether it may be starting point or the ending point

TypeError: 'float' object cannot be interpreted as an integer

In [83]:
# inside the numpy we have arange() which will takes the fractions as inputs

In [86]:
np.arange(0.4,10.4) # here stepsize is 1 by default
#arange is alternative of range function here

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [87]:
# we can also give the stepsize whatever we want here.
np.arange(0.4,9.4,0.5)

array([0.4, 0.9, 1.4, 1.9, 2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4, 5.9, 6.4,
       6.9, 7.4, 7.9, 8.4, 8.9])

In [88]:
# we can also convert to list above array 
list(np.arange(0.2,5.6,0.4))

[0.2,
 0.6000000000000001,
 1.0000000000000002,
 1.4000000000000001,
 1.8000000000000003,
 2.2000000000000006,
 2.6000000000000005,
 3.000000000000001,
 3.400000000000001,
 3.8000000000000007,
 4.200000000000001,
 4.600000000000001,
 5.000000000000001,
 5.400000000000001]

In [92]:
np.linspace(1,10,15) # divides the range in the equal 15 intervals

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [95]:
np.logspace(1,6,23) # divides the range in he logarithmic format in equal intervals

array([1.00000000e+01, 1.68761248e+01, 2.84803587e+01, 4.80638086e+01,
       8.11130831e+01, 1.36887451e+02, 2.31012970e+02, 3.89860370e+02,
       6.57933225e+02, 1.11033632e+03, 1.87381742e+03, 3.16227766e+03,
       5.33669923e+03, 9.00628020e+03, 1.51991108e+04, 2.56502091e+04,
       4.32876128e+04, 7.30527154e+04, 1.23284674e+05, 2.08056754e+05,
       3.51119173e+05, 5.92553098e+05, 1.00000000e+06])

In [96]:
# by default the base is 10
# we can also give the required base here.
np.logspace(1,6,23,base=2)


array([ 2.        ,  2.34123983,  2.74070197,  3.20832031,  3.75572364,
        4.39652489,  5.14665959,  6.02478221,  7.05273004,  8.25606624,
        9.66471556, 11.3137085 , 13.24405248, 15.50375158, 18.14900036,
       21.24558125, 24.87050051, 29.11390318, 34.08131486, 39.8962659 ,
       46.70336338, 54.67188726, 64.        ])

In [97]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [100]:
print(np.zeros((5,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [103]:
np.zeros((3,4,2)) # 3 matrices with 4*2 size

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [104]:
np.zeros((3,3,4,2)) 

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [105]:
print(np.ones(4))

[1. 1. 1. 1.]


In [108]:
print(np.ones((4,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [109]:
a=np.ones((4,5))

In [111]:
a+5 # adds 5 to each and every element

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [112]:
a*4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [114]:
print(np.empty((4,3)))

[[1.38311361e-311 2.86558075e-322 0.00000000e+000]
 [0.00000000e+000 1.06099790e-312 1.33664410e+160]
 [4.47207664e-090 9.50811928e-043 3.61256368e+174]
 [2.90203561e-057 6.48224659e+170 5.82471487e+257]]


In [120]:
arr1=np.eye(3) # identity matrix

In [123]:
arr1


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [122]:
# represent the data in th dataframe format
import pandas as pd
pd.DataFrame(arr1)

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [125]:
np.random.rand(2,4)

array([[0.46261498, 0.37846821, 0.44938694, 0.17172153],
       [0.11339801, 0.34109911, 0.02155263, 0.99269481]])

In [127]:
np.random.randn(3,4) # use randn when u want normally distributed data 

array([[ 1.27971999,  0.11841253,  0.74102318, -1.59672749],
       [ 0.3641919 ,  0.26278567,  0.63197858,  0.30396168],
       [-0.02280083,  0.07061526, -0.68517253,  1.96601806]])

In [129]:
arr1=np.random.randint(1,6,(3,3))

In [130]:
print(arr1)

[[4 4 4]
 [4 5 1]
 [2 2 5]]


In [131]:
print(arr1.size)

9


In [132]:
print(arr1.shape) 

(3, 3)


In [134]:
# whenever we perform reshape, it must be of same size which means 9 elements only should present in it
arr1.reshape(1,9)

array([[4, 4, 4, 4, 5, 1, 2, 2, 5]])

In [136]:
arr1.reshape(3,9)
# we get error since reshape given is not exact size of arr1

ValueError: cannot reshape array of size 9 into shape (3,9)

In [137]:
arr1.reshape(1,9,1)

array([[[4],
        [4],
        [4],
        [4],
        [5],
        [1],
        [2],
        [2],
        [5]]])

In [138]:
ar2=np.random.randint(1,20,(4,5))

In [139]:
ar2

array([[ 6, 14, 17, 12,  6],
       [10,  5,  7, 16, 11],
       [ 2,  6, 10,  5,  8],
       [ 2, 13, 11, 16, 14]])

In [140]:
ar2>5

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [145]:
ar2[ar2>5]

array([ 6, 14, 17, 12,  6, 10,  7, 16, 11,  6, 10,  8, 13, 11, 16, 14])

In [146]:
ar2

array([[ 6, 14, 17, 12,  6],
       [10,  5,  7, 16, 11],
       [ 2,  6, 10,  5,  8],
       [ 2, 13, 11, 16, 14]])

In [151]:
# extracting the data 
ar2[0]

array([ 6, 14, 17, 12,  6])

In [152]:
ar2[0,[0,1]]

array([ 6, 14])

In [153]:
ar2[[0,1],2]

array([17,  7])

In [154]:
ar2[2:4,[2,3]]

array([[10,  5],
       [11, 16]])

In [155]:
a1=np.random.randint(2,7,(4,4))

In [156]:
a2=np.random.randint(1,8,(4,4))

In [157]:
a1

array([[4, 3, 4, 2],
       [5, 4, 3, 4],
       [4, 2, 6, 4],
       [5, 4, 4, 2]])

In [158]:
a2

array([[4, 3, 4, 7],
       [5, 4, 3, 2],
       [1, 4, 2, 6],
       [7, 7, 2, 4]])

In [160]:
c=a1+a2

In [161]:
print(c)

[[ 8  6  8  9]
 [10  8  6  6]
 [ 5  6  8 10]
 [12 11  6  6]]


In [162]:
print(a1-a2)

[[ 0  0  0 -5]
 [ 0  0  0  2]
 [ 3 -2  4 -2]
 [-2 -3  2 -2]]


In [164]:
print(a1*a2) # here it gives index wise multiplication not the matrix multiplication

[[16  9 16 14]
 [25 16  9  8]
 [ 4  8 12 24]
 [35 28  8  8]]


In [167]:
a1@a2 # use @ for matrix multiplication

array([[49, 54, 37, 66],
       [71, 71, 46, 77],
       [60, 72, 42, 84],
       [58, 61, 44, 75]])

In [168]:
a1/a2

array([[1.        , 1.        , 1.        , 0.28571429],
       [1.        , 1.        , 1.        , 2.        ],
       [4.        , 0.5       , 3.        , 0.66666667],
       [0.71428571, 0.57142857, 2.        , 0.5       ]])

In [170]:
a1/0 # in numpy if we divide by zero,we get infinity

C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_10140\1168174942.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a1/0 # in numpy if we divide by zero,we get infinity


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

# Numpy-Broadcasting

In [183]:
# simply broadcasting a element to all the elements in the matrix
arr=np.zeros((3,4))


In [208]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [209]:
arr+5 # broadcasting 5 to all elements

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [210]:
arr*5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [211]:
a=np.array([1,2,3,4])

In [212]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [219]:
b=np.array([3,4,5])

In [222]:
b

array([3, 4, 5])

In [221]:
# we need to rotate the array first to perform column wise addition

In [217]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [223]:
b.T

array([3, 4, 5])

In [224]:
b.T

array([3, 4, 5])

In [225]:
np.sqrt(arr1)

array([[2.        , 2.        , 2.        ],
       [2.        , 2.23606798, 1.        ],
       [1.41421356, 1.41421356, 2.23606798]])

In [226]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.60205999],
       [0.60205999, 0.69897   , 0.        ],
       [0.30103   , 0.30103   , 0.69897   ]])

In [227]:
np.exp(arr1)

array([[ 54.59815003,  54.59815003,  54.59815003],
       [ 54.59815003, 148.4131591 ,   2.71828183],
       [  7.3890561 ,   7.3890561 , 148.4131591 ]])

In [228]:
np.min(arr1)

1

In [229]:
np.max(arr1)

5